### PR TITLE
Fix BuildVariables method in SqlPackageRunner

### PR DESCRIPTION
**Pull request by Myslik**
https://msdn.microsoft.com/library/hh550080(vs.103).aspx#Anchor_7
According to this reference correct switch for variables is **v**

### CODE REVIEW

**Comment by RLittlesII** [comment]
@Myslik Good catch.  Can you do me a favor and open an issue for this PR?  Also, would you mind fixing the unit tests to reflect the fix?

**Comment by Myslik** [comment]
Sure thing!

**Comment by Myslik** [comment]
Thank you 👍

**Comment by RLittlesII** [comment]
You're welcome.  I'm going to be working to get a release out over the next week.

**Pull request merged**
